### ISSUE TITLE
Mobile Issue

### ISSUE THREAD

**Issue by kmaas2000** [jdeniau/jquery-image-uploader#5]
I'm currently using the jQuery-Image-uploader & everything works fine on my laptop but on my Samsung S7, I get an "Upload Failed" error message. Any advice?

**Comment by kmaas2000** [comment]
It seems to be a file size issue, so i set maxFileSize: 0 but i'm still getting an error when uploading large image files.

**Comment by jdeniau** [comment]
Did you try different browser or are your using the Samsung navigator?

**Comment by kmaas2000** [comment]
I initially tried in chrome and just tried with Firefox and got the same
result.

**Comment by jdeniau** [comment]
I imagine that you tried different images too ? 

Did you checked your server log ?

**Comment by kmaas2000** [comment]
Yes, i've tried a number of images. Smaller ones behave as expected but large ones fail. Can't find any related errors in log files

**Comment by jdeniau** [comment]
Can you try uploading an image here: https://www.mapado.com/en/create-activity in the "media" section ? (no need to post the form, just try uploading an image and see if the image is well uploaded)

Additionally, can you give me the url of your form ?

Thanks

**Comment by kmaas2000** [comment]
Just tried & it failed: "The upload of your media has failed"

<img width="1156" alt="screen shot 2018-01-03 at 9 47 36 am" src="https://user-images.githubusercontent.com/34949636/34527454-3776b246-f06b-11e7-8c47-57eb144c44fe.png">

**Comment by kmaas2000** [comment]
The file is 8mb...too big?

I was able to upload an image from my phone that would not upload on my site. Cannot provide url to my form as it is not publicly available

**Comment by jdeniau** [comment]
Maybe, I think our limit is 4 or 5Mo

**Comment by jdeniau** [comment]
Maybe, I think our limit is 4 or 5Mo

**Comment by kmaas2000** [comment]
OK. Since i was able to upload an image from my phone on your site that won't upload on my site from my phone, what can i check to try and get it to work?

**Comment by kmaas2000** [comment]
I believe i figured out the issue. The default server upload limit is 2mb, so i increased the limit & that solved the issue

**Comment by kmaas2000** [comment]
What are some example file size limit values i can use? I can't find any examples & anytime i use anything other than 0 i get a js error.
